//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int StudId { get; set; }
        public Nullable<decimal> TenthMarks { get; set; }
        public Nullable<decimal> TwelthMarks { get; set; }
        public string TenthLink { get; set; }
        public string TwelthLink { get; set; }
        public Nullable<decimal> PolytechnicMarks { get; set; }
        public string PolytechnicLink { get; set; }
        public Nullable<decimal> BEPercentage { get; set; }
        public string FirstSemLink { get; set; }
        public string SecondSemLink { get; set; }
        public string ThirdSemLink { get; set; }
        public string ForthSemLink { get; set; }
        public string FifthSemLinkk { get; set; }
        public string SixthSemLink { get; set; }
        public string SeventhSemLink { get; set; }
        public string EigthSemLink { get; set; }
        public int EID { get; set; }
        public Nullable<int> CurrentBacklog { get; set; }
        public Nullable<int> TotalBacklog { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
