//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int NID { get; set; }
        public Nullable<int> TID { get; set; }
        public string SubOfNotice { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string Category { get; set; }
        public string link { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
