//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public int WID { get; set; }
        public int StudId { get; set; }
        public string Technology { get; set; }
        public string Organizer { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DateOfWorkshop { get; set; }
        public string Link { get; set; }
        public Nullable<int> Semester { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
